<a href="https://colab.research.google.com/github/Nirmalkumar1911/Variable/blob/main/Mobile_Price_range_Classification_with_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Mobile Price Range Determination**

1.Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.Importing and Compiling Dataset

In [2]:
train_set = pd.read_csv('train.csv')
test_set = pd.read_csv('test.csv')
train_set.head()

   battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [3]:
test_set = test_set.iloc[:,1:]
test_set.head()

   battery_power  blue  clock_speed  ...  three_g  touch_screen  wifi
0           1043     1          1.8  ...        0             1     0
1            841     1          0.5  ...        1             0     0
2           1807     1          2.8  ...        0             1     1
3           1546     0          0.5  ...        1             1     0
4           1434     0          1.4  ...        1             0     1

[5 rows x 20 columns]

3.Splitting the Training data Testing Accuracy

In [4]:
x = train_set.iloc[:,:-1]
y = train_set.iloc[:,-1]
from sklearn.model_selection import train_test_split as tts
x_train , x_test , y_train , y_test = tts(x,y,test_size=0.25,random_state = 0)

In [5]:
x_train

      battery_power  blue  clock_speed  ...  three_g  touch_screen  wifi
1045            531     0          1.1  ...        0             1     0
937             764     1          1.2  ...        1             1     0
1658           1812     1          1.3  ...        1             1     1
529            1821     0          0.9  ...        1             1     1
895            1790     1          2.3  ...        1             0     1
...             ...   ...          ...  ...      ...           ...   ...
835            1224     1          1.6  ...        1             1     0
1216           1158     0          0.7  ...        1             0     1
1653           1190     0          2.0  ...        0             0     1
559            1191     0          2.4  ...        1             1     1
684             706     0          0.5  ...        1             0     1

[1500 rows x 20 columns]

In [6]:
y_train

1045    2
937     2
1658    3
529     2
895     3
       ..
835     3
1216    1
1653    3
559     0
684     1
Name: price_range, Length: 1500, dtype: int64

4.Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test= sc.transform(x_test)
test_set = sc.transform(test_set)

5.Training the Model

In [8]:
from sklearn.linear_model import LogisticRegression as lr
classifier = lr(random_state = 0)
classifier.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

6.Finding the matrix of Predicted and Actual Values of training data

In [9]:
y_pred = classifier.predict(x_test)
y_pred = y_pred.reshape(len(y_pred),1)
y_test = np.array(y_test)
y_test = y_test.reshape(len(y_test),1)
print(np.concatenate((y_pred,y_test),1))

[[3 3]
 [0 0]
 [2 2]
 [2 2]
 [3 2]
 [0 0]
 [0 0]
 [3 3]
 [3 3]
 [1 1]
 [1 1]
 [3 3]
 [0 0]
 [2 2]
 [3 3]
 [0 0]
 [3 3]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [0 0]
 [3 3]
 [1 1]
 [2 2]
 [2 2]
 [3 3]
 [1 1]
 [3 3]
 [1 1]
 [1 1]
 [0 0]
 [2 2]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [0 0]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [0 0]
 [1 1]
 [3 3]
 [1 1]
 [1 1]
 [3 3]
 [0 0]
 [3 3]
 [0 0]
 [2 3]
 [2 2]
 [2 2]
 [0 0]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [2 2]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [2 2]
 [1 1]
 [0 0]
 [1 1]
 [3 3]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [1 1]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [3 3]
 [3 3]
 [3 3]
 [0 0]
 [3 3]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [3 3]
 [2 2]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [3 3]
 [2 2]
 [2 2]
 [1 1]
 [2 1]
 [1 1]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [3 3]
 [3 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [0 0]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [3 3]
 [0 1]
 [3 3]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [0 0]
 [0 0]
 [3 3]
 [1 1]
 [3 3]
 [2 2]
 [1 1]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [3 3]
 [2 2]
 [1 1]
 [0 0]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [3 3]
 [0 0]
 [2 2]
 [2 2]
 [3 3]
 [1 0]
 [2 2]
 [1 1]
 [0 0]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [0 0]
 [3 3]
 [3 3]
 [1 1]
 [1 1]
 [0 0]
 [2 2]
 [3 3]
 [0 0]
 [1 1]
 [2 2]
 [2 2]
 [0 0]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [3 3]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [2 1]
 [3 3]
 [3 3]
 [3 3]
 [0 0]
 [0 0]
 [2 2]
 [3 3]
 [3 3]
 [1 1]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [3 3]
 [2 2]
 [1 0]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [0 0]
 [2 2]
 [3 3]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [3 3]
 [1 2]
 [3 3]
 [0 0]
 [3 3]
 [1 1]
 [1 1]
 [0 0]
 [2 2]
 [3 3]
 [3 3]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [3 3]
 [1 2]
 [1 1]
 [0 0]
 [3 3]
 [3 3]
 [2 2]
 [1 1]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [3 2]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [2 1]
 [2 2]
 [3 3]
 [0 0]
 [2 2]
 [0 0]
 [1 1]
 [1 1]
 [3 3]
 [0 0]
 [0 0]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [0 0]
 [2 2]
 [0 0]
 [3 3]
 [0 0]
 [3 3]
 [3 3]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [2 1]
 [0 0]
 [1 1]
 [0 0]
 [3 3]
 [1 1]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [3 3]
 [1 1]
 [1 2]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [2 2]
 [1 2]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [3 3]
 [2 2]
 [2 2]
 [1 1]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [0 0]
 [2 2]
 [0 0]
 [3 3]
 [0 0]
 [1 1]
 [1 1]
 [2 2]
 [3 2]
 [1 1]
 [3 3]
 [1 1]
 [2 2]
 [0 0]
 [1 1]
 [2 2]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [3 3]
 [0 0]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [0 0]
 [2 2]
 [0 1]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [3 3]
 [3 3]
 [0 0]
 [2 2]
 [1 1]
 [3 3]
 [1 1]
 [1 1]
 [3 3]
 [2 2]
 [0 0]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [0 0]
 [3 3]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [0 0]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [0 0]
 [3 3]
 [3 3]
 [0 0]
 [3 3]
 [3 3]
 [0 0]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [2 2]
 [1 1]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [0 0]
 [3 3]
 [3 3]
 [2 2]
 [1 1]
 [0 0]
 [3 3]
 [1 1]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [1 2]
 [2 2]
 [0 0]
 [1 1]
 [3 3]
 [0 0]
 [3 3]
 [2 2]
 [1 1]
 [2 2]
 [0 0]
 [3 3]
 [0 1]
 [2 2]
 [3 3]
 [2 2]]

7.Finding the Confusion Matrix and Accuracy Score

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[122   2   0   0]
 [  3 103   4   0]
 [  0   5 116   4]
 [  0   0   1 140]]

0.962

8.Predicting a Singular Result

In [11]:
print(classifier.predict(sc.transform([[1500,1,2,1,20,1,64,.9,200,4,20,1270,1752,4000,15,10,10,1,1,1]])))

[3]

9.Predicting the Test Set

In [12]:
y_actual_pred = classifier.predict(test_set) 
y_actual_pred

array([3, 3, 2, 3, 1, 3, 3, 1, 3, 0, 3, 3, 0, 0, 2, 0, 2, 1, 3, 2, 1, 3,
       1, 1, 3, 0, 2, 0, 3, 0, 2, 0, 3, 0, 1, 1, 3, 1, 2, 1, 1, 2, 0, 0,
       0, 1, 0, 3, 1, 2, 1, 0, 3, 0, 3, 1, 3, 1, 1, 3, 3, 3, 0, 1, 1, 1,
       2, 3, 1, 2, 1, 2, 2, 3, 3, 0, 2, 0, 1, 3, 0, 3, 3, 0, 3, 0, 3, 1,
       3, 0, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 0, 0, 3, 0, 2, 0, 1, 2, 3,
       3, 3, 1, 3, 3, 3, 3, 2, 3, 0, 0, 3, 2, 1, 2, 0, 3, 2, 2, 2, 0, 2,
       2, 1, 3, 1, 1, 0, 3, 2, 1, 2, 1, 3, 2, 3, 3, 3, 2, 3, 2, 3, 1, 0,
       3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 0, 3, 0, 0, 0, 2, 1, 0, 1,
       0, 0, 1, 2, 1, 0, 0, 1, 1, 2, 2, 1, 0, 0, 0, 1, 0, 3, 1, 0, 2, 2,
       2, 3, 1, 2, 3, 2, 3, 2, 2, 1, 1, 0, 1, 2, 0, 2, 3, 3, 0, 2, 0, 3,
       2, 3, 3, 1, 0, 1, 0, 3, 0, 1, 0, 2, 2, 1, 3, 1, 2, 0, 3, 1, 2, 0,
       0, 2, 1, 3, 3, 3, 1, 1, 3, 0, 0, 2, 3, 3, 1, 3, 1, 1, 3, 2, 1, 2,
       3, 3, 3, 1, 0, 0, 2, 3, 1, 1, 3, 2, 1, 3, 0, 0, 3, 1, 0, 3, 2, 3,
       3, 2, 1, 3, 3, 2, 3, 1, 2, 1, 2, 0, 2, 3, 1, 0, 0, 3, 0, 3, 0, 1,
       2, 0, 2, 3, 1, 3, 2, 2, 1, 2, 0, 0, 0, 1, 3, 2, 0, 0, 0, 3, 2, 0,
       2, 3, 1, 2, 2, 2, 3, 1, 3, 3, 2, 2, 2, 3, 3, 0, 3, 1, 3, 1, 3, 1,
       2, 3, 0, 1, 0, 3, 1, 3, 2, 3, 0, 0, 0, 0, 2, 0, 0, 2, 2, 1, 2, 2,
       2, 0, 1, 0, 0, 3, 2, 0, 3, 1, 2, 2, 1, 2, 3, 1, 1, 2, 2, 1, 2, 0,
       1, 1, 0, 3, 2, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 2, 3, 2, 3, 0, 3,
       0, 3, 0, 1, 1, 0, 2, 0, 3, 2, 3, 3, 1, 3, 1, 3, 1, 2, 2, 0, 1, 2,
       1, 1, 0, 0, 0, 1, 2, 1, 0, 3, 2, 0, 2, 2, 0, 0, 3, 1, 2, 0, 2, 3,
       3, 0, 3, 0, 2, 3, 2, 3, 0, 2, 0, 2, 2, 0, 1, 1, 0, 0, 1, 2, 1, 3,
       3, 3, 2, 3, 1, 2, 2, 3, 3, 3, 2, 0, 2, 1, 2, 2, 1, 0, 2, 2, 0, 0,
       0, 3, 1, 0, 2, 2, 2, 0, 3, 1, 2, 2, 1, 3, 0, 2, 3, 0, 1, 1, 3, 3,
       2, 1, 2, 3, 2, 0, 2, 0, 2, 0, 3, 3, 1, 3, 2, 2, 3, 0, 1, 2, 3, 1,
       3, 2, 3, 1, 1, 0, 0, 3, 1, 0, 3, 2, 3, 2, 0, 3, 3, 3, 2, 3, 3, 1,
       2, 0, 2, 2, 3, 1, 0, 1, 1, 2, 2, 2, 0, 0, 2, 2, 3, 2, 0, 2, 1, 3,
       3, 0, 1, 3, 0, 2, 1, 1, 0, 0, 2, 1, 0, 1, 1, 2, 2, 0, 2, 2, 1, 0,
       3, 0, 0, 3, 2, 0, 0, 0, 0, 0, 3, 0, 3, 1, 3, 1, 1, 3, 3, 0, 1, 0,
       3, 2, 2, 2, 1, 3, 0, 2, 0, 2, 0, 0, 1, 1, 1, 2, 1, 3, 1, 3, 2, 2,
       1, 3, 2, 0, 2, 2, 0, 3, 3, 0, 2, 1, 1, 2, 0, 3, 2, 0, 3, 2, 3, 0,
       0, 3, 0, 2, 2, 3, 2, 2, 2, 2, 1, 2, 3, 0, 1, 0, 1, 2, 1, 0, 0, 1,
       0, 0, 3, 1, 1, 2, 0, 1, 1, 1, 3, 0, 3, 2, 3, 0, 0, 1, 2, 2, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 3, 3, 0, 3, 1, 1, 3, 0, 1, 0, 2, 1, 0, 3, 1,
       0, 3, 0, 1, 0, 3, 3, 3, 2, 3, 0, 3, 2, 0, 0, 0, 3, 3, 2, 0, 2, 1,
       3, 0, 0, 2, 2, 0, 3, 1, 2, 1, 1, 1, 3, 1, 1, 1, 2, 1, 0, 2, 2, 0,
       2, 0, 0, 0, 0, 2, 3, 3, 3, 0, 1, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 3,
       2, 2, 1, 2, 0, 2, 1, 3, 0, 0, 3, 2, 3, 0, 0, 2, 3, 3, 1, 3, 2, 1,
       0, 0, 3, 3, 1, 3, 0, 0, 0, 2, 2, 1, 2, 0, 3, 2, 1, 2, 3, 3, 0, 1,
       1, 2, 1, 2, 2, 0, 1, 3, 1, 1, 3, 0, 2, 3, 2, 1, 1, 1, 3, 3, 0, 2,
       3, 0, 2, 3, 2, 2, 2, 3, 2, 0, 1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1,
       0, 1, 3, 1, 0, 1, 2, 3, 1, 0, 0, 3, 2, 2, 3, 0, 3, 3, 2, 1, 3, 0,
       1, 3, 1, 2, 1, 2, 3, 2, 0, 3, 0, 2, 3, 0, 3, 1, 3, 3, 1, 0, 2, 3,
       1, 0, 2, 1, 2, 1, 2, 0, 2, 2, 0, 2, 3, 2, 3, 0, 2, 1, 1, 2, 2, 3,
       3, 0, 2, 1, 2, 1, 3, 1, 0, 3, 0, 1, 0, 0, 3, 3, 2, 0, 0, 0, 0, 3,
       2, 3, 3, 0, 0, 2, 1, 0, 2, 2])